site_name: Documentação Interna DTI
site_description: Guia técnico e operacional dos sistemas da Diretoria de Tecnologia da Informação – 
site_url: http://10.10.1.116:8000

plugins:
  - search
  - gen-files:
      scripts:
        - scripts/gerador-indexes.py

theme:
  name: material
  custom_dir: overrides 
    # logo: assets/logo.png
  favicon: assets/favicon.ico
  palette:
    - scheme: default
      primary: blue
      accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - navigation.footer
    - toc.integrate
    - content.code.copy
    - content.action.edit
extra_css:
  - assets/extra.css
  - https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css

extra_javascript:
  - https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js

nav:
  - Início: index.md
  - Visão geral: visao-geral/index.md
  - Instalação:  instalacao/index.md
  - APIs: apis/index.md
  - Usuário final: usuario-final/index.md
  - Documentação: documentacao/index.md
